In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/Users/sanjayroberts1/Desktop/data_science_tools1/sudeste.csv')

In [3]:
df.head()

,wsid,wsnm,elvt,lat,lon,inme,city,prov,mdct,date,...,tmax,dmax,tmin,dmin,hmdy,hmax,hmin,wdsp,wdct,gust
0,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 00:00:00,2007-11-06,...,29.7,16.8,25.5,10.8,35.0,58.0,32.0,3.2,101.0,6.5
1,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 01:00:00,2007-11-06,...,29.9,13.6,29.0,12.2,39.0,39.0,35.0,3.6,94.0,6.4
2,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 02:00:00,2007-11-06,...,29.0,14.0,27.4,13.6,44.0,44.0,39.0,2.5,93.0,6.9
3,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 03:00:00,2007-11-06,...,27.4,16.9,25.8,14.1,58.0,58.0,44.0,1.7,96.0,5.8
4,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 04:00:00,2007-11-06,...,26.3,17.0,25.3,16.4,57.0,58.0,56.0,3.1,110.0,7.5

In [4]:
df.columns

Index(['wsid', 'wsnm', 'elvt', 'lat', 'lon', 'inme', 'city', 'prov', 'mdct',
       'date', 'yr', 'mo', 'da', 'hr', 'prcp', 'stp', 'smax', 'smin', 'gbrd',
       'temp', 'dewp', 'tmax', 'dmax', 'tmin', 'dmin', 'hmdy', 'hmax', 'hmin',
       'wdsp', 'wdct', 'gust'],
      dtype='object')

In [10]:
df.elvt.unique()

array([ 237.,    9.,  976.,   38.,   14.,   29.,  129.,   69.,  156.,
        507., 1169., 1018.,  646.,  875.,  189., 1545.,  698.,  493.,
        540., 1048.,  930.,  950.,  782.,  283.,  937.,  559.,  573.,
        854.,  212.,  978.,  878.,  913.,  520.,  467.,  931., 1017.,
       1077., 1281.,  198.,  853.,  288.,  754.,  721., 1359.,  669.,
        454.,  255.,  932.,  641.,  565.,  894.,  505.,  997.,  490.,
        873.,  272.,  850.,  487.,  877.,  609., 1199.,  819.,  411.,
        468.,  705.,  845.,  719., 1200.,   35.,   24.,   60.,    3.,
          7.,   25.,  439., 1758.,  367.,  991.,   30., 1065.,  305.,
        340.,   26.,   20.,   19.,  786.,  636., 1663.,  432., 1003.,
        859.,  743.,  676.,  443.,  399.,  776.,  566.,  461.,  582.,
        510.,  460.,  382.,  408.,  525.,  497.,  734.,  635.,  862.,
        534.,    0.,  660.,  611.,  777.])

In [18]:
df[['wsid', 'city','mdct',
       'date', 'yr', 'mo', 'da', 'hr', 'prcp', 'stp', 'smax', 'smin', 'gbrd',
       'temp']].head(20)

,wsid,city,mdct,date,yr,mo,da,hr,prcp,stp,smax,smin,gbrd,temp
0,178,São Gonçalo,2007-11-06 00:00:00,2007-11-06,2007,11,6,0,NaN,982.5,982.5,981.3,NaN,29.3
1,178,São Gonçalo,2007-11-06 01:00:00,2007-11-06,2007,11,6,1,NaN,983.2,983.2,982.5,NaN,29.0
2,178,São Gonçalo,2007-11-06 02:00:00,2007-11-06,2007,11,6,2,NaN,983.5,983.5,983.2,NaN,27.4
3,178,São Gonçalo,2007-11-06 03:00:00,2007-11-06,2007,11,6,3,NaN,983.7,983.7,983.4,NaN,25.8
4,178,São Gonçalo,2007-11-06 04:00:00,2007-11-06,2007,11,6,4,NaN,983.7,983.8,983.6,NaN,25.4
5,178,São Gonçalo,2007-11-06 05:00:00,2007-11-06,2007,11,6,5,NaN,983.7,983.8,983.6,NaN,23.8
6,178,São Gonçalo,2007-11-06 06:00:00,2007-11-06,2007,11,6,6,NaN,983.7,983.7,983.6,NaN,22.0
7,178,São Gonçalo,2007-11-06 07:00:00,2007-11-06,2007,11,6,7,NaN,984.6,984.6,983.7,NaN,19.7
8,178,São Gonçalo,2007-11-06 08:00:00,2007-11-06,2007,11,6,8,NaN,985.7,985.7,984.6,NaN,18.3
9,178,São Gonçalo,2007-11-06 09:00:00,2007-11-06,2007,11,6,9,NaN,986.7,986.7,985.7,214.149,22.9
10,178,São Gonçalo,2007-11-06 10:00:00,2007-11-06,2007,11,6,10,NaN,987.2,987.2,986.7,987.980,25.0
11,178,São Gonçalo,2007-11-06 11:00:00,2007-11-06,2007,11,6,11,0.0,0.0,0.0,0.0,0.000,0.0
12,178,São Gonçalo,2007-11-06 12:00:00,2007-11-06,2007,11,6,12,0.0,0.0,0.0,0.0,0.000,0.0
13,178,São Gonçalo,2007-11-06 13:00:00,2007-11-06,2007,11,6,13,0.0,0.0,0.0,0.0,0.000,0.0
14,178,São Gonçalo,2007-11-06 14:00:00,2007-11-06,2007,11,6,14,NaN,986.0,987.0,986.0,1513.621,31.0
15,178,São Gonçalo,2007-11-06 15:00:00,2007-11-06,2007,11,6,15,NaN,984.8,986.1,984.8,3700.385,32.7
16,178,São Gonçalo,2007-11-06 16:00:00,2007-11-06,2007,11,6,16,NaN,983.4,984.8,983.4,3484.193,33.7
17,178,São Gonçalo,2007-11-06 17:00:00,2007-11-06,2007,11,6,17,NaN,982.5,983.4,982.5,3088.712,34.7
18,178,São Gonçalo,2007-11-06 18:00:00,2007-11-06,2007,11,6,18,NaN,981.7,982.5,981.7,2286.388,34.3
19,178,São Gonçalo,2007-11-06 19:00:00,2007-11-06,2007,11,6,19,NaN,981.3,981.7,981.3,1421.169,34.7

In [20]:
df.shape

(9779168, 31)

In [4]:
df.tail(20)

,wsid,wsnm,elvt,lat,lon,inme,city,prov,mdct,date,...,tmax,dmax,tmin,dmin,hmdy,hmax,hmin,wdsp,wdct,gust
9779148,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 04:00:00,2016-09-30,...,14.9,12.3,14.7,11.3,84.0,85.0,80.0,0.0,0.0,0.0
9779149,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 05:00:00,2016-09-30,...,14.9,12.2,14.8,10.9,77.0,84.0,77.0,0.0,0.0,0.0
9779150,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 06:00:00,2016-09-30,...,14.9,11.6,14.6,10.9,81.0,81.0,77.0,0.0,0.0,0.0
9779151,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 07:00:00,2016-09-30,...,14.8,11.8,14.5,11.4,81.0,83.0,81.0,0.0,0.0,0.0
9779152,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 08:00:00,2016-09-30,...,14.9,11.8,14.6,11.3,80.0,82.0,79.0,0.0,0.0,0.0
9779153,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 09:00:00,2016-09-30,...,14.9,11.7,14.2,11.3,82.0,83.0,80.0,0.0,0.0,0.0
9779154,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 10:00:00,2016-09-30,...,15.8,11.4,14.3,11.1,74.0,82.0,74.0,0.0,0.0,0.0
9779155,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 11:00:00,2016-09-30,...,17.7,12.0,15.6,11.0,69.0,75.0,67.0,0.0,0.0,0.0
9779156,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 12:00:00,2016-09-30,...,19.3,12.0,17.1,10.6,60.0,69.0,58.0,0.0,0.0,0.0
9779157,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 13:00:00,2016-09-30,...,20.5,12.2,18.2,10.6,58.0,64.0,56.0,0.0,0.0,0.0
9779158,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 14:00:00,2016-09-30,...,21.4,12.5,19.4,9.8,55.0,62.0,51.0,0.0,0.0,0.0
9779159,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 15:00:00,2016-09-30,...,21.8,12.1,19.9,10.6,54.0,58.0,51.0,0.0,0.0,0.0
9779160,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 16:00:00,2016-09-30,...,21.4,12.8,20.2,11.5,59.0,60.0,54.0,0.0,0.0,0.0
9779161,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 17:00:00,2016-09-30,...,21.2,12.8,19.3,11.5,64.0,65.0,57.0,0.0,0.0,0.0
9779162,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 18:00:00,2016-09-30,...,19.5,12.8,18.0,11.8,67.0,68.0,64.0,0.0,0.0,0.0
9779163,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 19:00:00,2016-09-30,...,18.2,12.4,16.3,11.8,76.0,77.0,67.0,0.0,0.0,0.0
9779164,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 20:00:00,2016-09-30,...,16.8,12.5,15.3,11.7,80.0,80.0,75.0,0.0,0.0,0.0
9779165,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 21:00:00,2016-09-30,...,15.3,11.9,14.9,11.5,79.0,81.0,79.0,0.0,0.0,0.0
9779166,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 22:00:00,2016-09-30,...,15.0,11.7,14.4,11.4,82.0,83.0,79.0,0.0,0.0,0.0
9779167,423,BARUERI,777.0,-23.52389,-46.86945,A755,Barueri,SP,2016-09-30 23:00:00,2016-09-30,...,14.6,11.5,14.3,11.2,82.0,82.0,81.0,0.0,0.0,0.0

In [5]:
df.head(20)

,wsid,wsnm,elvt,lat,lon,inme,city,prov,mdct,date,...,tmax,dmax,tmin,dmin,hmdy,hmax,hmin,wdsp,wdct,gust
0,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 00:00:00,2007-11-06,...,29.7,16.8,25.5,10.8,35.0,58.0,32.0,3.2,101.0,6.5
1,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 01:00:00,2007-11-06,...,29.9,13.6,29.0,12.2,39.0,39.0,35.0,3.6,94.0,6.4
2,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 02:00:00,2007-11-06,...,29.0,14.0,27.4,13.6,44.0,44.0,39.0,2.5,93.0,6.9
3,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 03:00:00,2007-11-06,...,27.4,16.9,25.8,14.1,58.0,58.0,44.0,1.7,96.0,5.8
4,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 04:00:00,2007-11-06,...,26.3,17.0,25.3,16.4,57.0,58.0,56.0,3.1,110.0,7.5
5,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 05:00:00,2007-11-06,...,25.4,16.4,23.8,16.0,62.0,62.0,57.0,2.0,99.0,6.8
6,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 06:00:00,2007-11-06,...,23.8,16.7,22.0,16.2,72.0,72.0,62.0,1.3,93.0,4.9
7,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 07:00:00,2007-11-06,...,22.0,17.8,19.5,16.6,86.0,89.0,72.0,0.5,157.0,2.8
8,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 08:00:00,2007-11-06,...,19.7,17.3,18.3,16.9,93.0,94.0,85.0,NaN,141.0,1.5
9,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 09:00:00,2007-11-06,...,22.9,18.3,18.2,17.1,75.0,94.0,75.0,NaN,248.0,NaN
10,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 10:00:00,2007-11-06,...,25.1,18.4,22.9,17.0,61.0,76.0,61.0,3.3,97.0,6.2
11,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 11:00:00,2007-11-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 12:00:00,2007-11-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 13:00:00,2007-11-06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 14:00:00,2007-11-06,...,31.8,16.0,30.0,14.3,36.0,42.0,36.0,3.2,97.0,9.1
15,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 15:00:00,2007-11-06,...,33.0,15.4,31.0,13.6,32.0,37.0,31.0,3.8,103.0,8.6
16,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 16:00:00,2007-11-06,...,34.0,15.6,32.5,12.9,31.0,34.0,29.0,3.7,78.0,9.6
17,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 17:00:00,2007-11-06,...,34.7,14.6,33.4,12.2,29.0,31.0,27.0,2.8,102.0,9.0
18,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 18:00:00,2007-11-06,...,35.2,14.2,33.9,12.6,27.0,29.0,26.0,2.5,94.0,9.0
19,178,SÃO GONÇALO,237.0,-6.835777,-38.311583,A333,São Gonçalo,RJ,2007-11-06 19:00:00,2007-11-06,...,35.1,14.5,33.7,12.6,28.0,30.0,26.0,2.9,93.0,8.5

In [7]:
x = df.columns

In [10]:
x

Index(['wsid', 'wsnm', 'elvt', 'lat', 'lon', 'inme', 'city', 'prov', 'mdct',
       'date', 'yr', 'mo', 'da', 'hr', 'prcp', 'stp', 'smax', 'smin', 'gbrd',
       'temp', 'dewp', 'tmax', 'dmax', 'tmin', 'dmin', 'hmdy', 'hmax', 'hmin',
       'wdsp', 'wdct', 'gust'],
      dtype='object')

In [23]:
df[['yr', 'mo', 'da', 'hr', 'prcp', 'stp', 'smax', 'smin', 'gbrd', 'temp', 'dewp']].head(10)

     yr  mo  da  hr  prcp    stp   smax   smin     gbrd  temp  dewp
0  2007  11   6   0   NaN  982.5  982.5  981.3      NaN  29.3  12.1
1  2007  11   6   1   NaN  983.2  983.2  982.5      NaN  29.0  13.5
2  2007  11   6   2   NaN  983.5  983.5  983.2      NaN  27.4  14.0
3  2007  11   6   3   NaN  983.7  983.7  983.4      NaN  25.8  16.9
4  2007  11   6   4   NaN  983.7  983.8  983.6      NaN  25.4  16.4
5  2007  11   6   5   NaN  983.7  983.8  983.6      NaN  23.8  16.2
6  2007  11   6   6   NaN  983.7  983.7  983.6      NaN  22.0  16.7
7  2007  11   6   7   NaN  984.6  984.6  983.7      NaN  19.7  17.4
8  2007  11   6   8   NaN  985.7  985.7  984.6      NaN  18.3  17.3
9  2007  11   6   9   NaN  986.7  986.7  985.7  214.149  22.9  18.3