In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
df = pd.read_hdf('cleaning_up_df.hdf','mydata')

Let's see what the warmest and coldest temperatures for each year and which city it happens in:

In [113]:
index = []
year = []
city = []
tmax = []

for i in df.yr.unique():
    k = df.loc[df['yr'] == int(i)].tmax.nlargest()
    for w in range(5):
        try:
            g = df.loc[k.index[w]][df.loc[k.index[w]].tmax == k[w]]
            city.append(g.iloc[0]['city'])
            year.append(i)
            index.append(k.index[w])
            tmax.append(k[w])
        except:
            pass
        
df1 = pd.DataFrame({'date': index,'city': city,'tmax': tmax, 'year':year})
df1

                  date             city  tmax  year
0  2007-10-29 17:00:00      Montalvânia  40.2  2007
1  2007-11-02 17:00:00          Itaobim  40.0  2007
2  2007-10-28 19:00:00      Montalvânia  39.7  2007
3  2007-11-20 17:00:00      Montalvânia  39.7  2007
4  2007-11-20 18:00:00      Montalvânia  39.7  2007
5  2008-10-28 18:00:00      Porteirinha  41.3  2008
6  2008-10-28 19:00:00        São Romão  41.0  2008
7  2008-10-28 17:00:00        São Romão  40.8  2008
8  2008-10-28 18:00:00        São Romão  40.8  2008
9  2008-11-06 17:00:00      Montalvânia  40.7  2008
10 2009-09-02 18:00:00     Nova Venécia  44.3  2009
11 2009-03-15 19:00:00          Itaobim  40.1  2009
12 2009-03-15 18:00:00          Itaobim  39.9  2009
13 2009-03-15 20:00:00          Itaobim  39.7  2009
14 2009-09-29 18:00:00          Itaobim  39.7  2009
15 2010-11-20 16:00:00         Ariranha  41.9  2010
16 2010-11-20 17:00:00         Ariranha  41.7  2010
17 2010-02-24 19:00:00          Cambuci  41.0  2010
18 2010-02-09 15:00:00            Macaé  40.8  2010
19 2010-02-24 17:00:00           Alegre  40.6  2010
20 2011-08-12 19:00:00       Valparaíso  44.3  2011
21 2011-08-12 20:00:00       Valparaíso  43.4  2011
22 2011-08-12 18:00:00       Valparaíso  42.2  2011
23 2011-08-12 17:00:00       Valparaíso  41.6  2011
24 2011-08-12 16:00:00       Valparaíso  40.9  2011
25 2012-03-02 18:00:00   Afonso Cláudio  45.0  2012
26 2012-04-24 13:00:00         Pirapora  44.8  2012
27 2012-05-11 14:00:00         Pirapora  44.8  2012
28 2012-02-12 18:00:00   Afonso Cláudio  44.6  2012
29 2012-03-04 17:00:00   Afonso Cláudio  44.6  2012
30 2013-12-20 11:00:00        São Romão  45.0  2013
31 2013-12-28 00:00:00        São Romão  44.0  2013
32 2013-08-23 17:00:00       Valparaíso  43.9  2013
33 2013-12-22 13:00:00        São Romão  42.4  2013
34 2013-08-23 19:00:00       Valparaíso  42.1  2013
35 2014-01-04 15:00:00        São Romão  43.9  2014
36 2014-02-17 13:00:00         Espinosa  43.1  2014
37 2014-01-03 14:00:00        São Romão  42.7  2014
38 2014-10-13 17:00:00       Seropédica  41.7  2014
39 2014-10-13 17:00:00   Rio de Janeiro  41.6  2014
40 2015-10-16 15:00:00   Rio de Janeiro  42.4  2015
41 2015-10-16 16:00:00   Rio de Janeiro  42.2  2015
42 2015-10-15 17:00:00   Rio de Janeiro  42.1  2015
43 2015-10-16 17:00:00   Rio de Janeiro  42.1  2015
44 2015-10-24 15:00:00         Barretos  41.8  2015
45 2016-01-02 19:00:00          Itaobim  42.3  2016
46 2016-01-02 19:00:00         Almenara  42.1  2016
47 2016-01-02 17:00:00          Itaobim  42.1  2016
48 2016-01-02 18:00:00          Itaobim  41.9  2016
49 2016-01-02 21:00:00          Itaobim  41.8  2016
50 2006-01-25 19:00:00  Duque de Caxias  40.5  2006
51 2006-01-25 20:00:00          Cambuci  40.5  2006
52 2006-01-25 18:00:00  Duque de Caxias  40.2  2006
53 2006-01-26 19:00:00          Cambuci  39.9  2006
54 2006-01-25 17:00:00  Duque de Caxias  39.7  2006
55 2003-03-02 17:00:00       Seropédica  39.5  2003
56 2003-02-13 17:00:00   Rio de Janeiro  39.2  2003
57 2003-02-13 16:00:00   Rio de Janeiro  39.1  2003
58 2003-03-02 19:00:00  Duque de Caxias  39.0  2003
59 2003-02-13 19:00:00  Duque de Caxias  38.9  2003
60 2004-01-23 13:00:00   Rio de Janeiro  39.6  2004
61 2004-01-23 14:00:00   Rio de Janeiro  39.0  2004
62 2004-10-31 18:00:00   Rio de Janeiro  38.8  2004
63 2004-11-05 16:00:00   Rio de Janeiro  38.8  2004
64 2004-11-05 17:00:00       Seropédica  38.3  2004
65 2005-10-14 17:00:00   Rio de Janeiro  40.2  2005
66 2005-10-14 19:00:00  Duque de Caxias  39.8  2005
67 2005-10-14 18:00:00  Duque de Caxias  39.7  2005
68 2005-10-14 18:00:00       Seropédica  39.5  2005
69 2005-10-14 19:00:00       Seropédica  39.5  2005
70 2002-12-01 18:00:00   Rio de Janeiro  40.9  2002
71 2002-12-01 17:00:00   Rio de Janeiro  40.8  2002
72 2002-12-01 16:00:00   Rio de Janeiro  39.9  2002
73 2002-10-16 17:00:00       Seropédica  39.7  2002
74 2002-12-01 19:00:00       Seropédica  39.6  2002

In [115]:
index = []
city = []
tmin = []
year = []

for i in df.yr.unique():
    k = df.loc[df['yr'] == int(i)].tmin.nsmallest()
    for w in range(5):
        try:
            g = df.loc[k.index[w]][df.loc[k.index[w]].tmin == k[w]]
            city.append(g.iloc[0]['city'])
            year.append(i)
            index.append(k.index[w])
            tmin.append(k[w])
        except:
            pass
        
df2 = pd.DataFrame({'date': index,'city': city,'tmin': tmin,'year':year})
df2

                  date              city  tmin  year
0  2007-07-30 10:00:00  Campos do Jordão  -2.3  2007
1  2007-07-30 09:00:00  Campos do Jordão  -1.6  2007
2  2007-07-30 11:00:00  Campos do Jordão  -1.6  2007
3  2007-07-30 08:00:00       Camanducaia  -1.1  2007
4  2007-07-30 10:00:00       Maria da Fé  -1.0  2007
5  2008-07-15 10:00:00       Camanducaia  -2.2  2008
6  2008-07-15 09:00:00       Camanducaia  -2.0  2008
7  2008-07-15 11:00:00       Camanducaia  -1.8  2008
8  2008-07-15 08:00:00       Camanducaia  -1.7  2008
9  2008-07-16 10:00:00       Camanducaia  -1.7  2008
10 2009-06-04 11:00:00       Camanducaia  -1.8  2009
11 2009-06-04 02:00:00       Camanducaia  -1.6  2009
12 2009-06-04 03:00:00       Camanducaia  -1.6  2009
13 2009-06-04 09:00:00       Camanducaia  -1.3  2009
14 2009-06-04 10:00:00       Camanducaia  -1.2  2009
15 2010-08-18 10:00:00       Camanducaia  -2.7  2010
16 2010-08-18 11:00:00       Camanducaia  -2.5  2010
17 2010-08-18 08:00:00       Camanducaia  -2.1  2010
18 2010-08-07 10:00:00       Camanducaia  -2.0  2010
19 2010-08-07 09:00:00       Camanducaia  -1.8  2010
20 2011-06-28 11:00:00         Rancharia  -3.7  2011
21 2011-08-05 07:00:00       Camanducaia  -3.6  2011
22 2011-06-28 10:00:00         Rancharia  -3.6  2011
23 2011-08-05 05:00:00       Camanducaia  -3.5  2011
24 2011-08-05 06:00:00       Camanducaia  -3.5  2011
25 2012-05-07 08:00:00          Pirapora  -8.5  2012
26 2012-05-09 22:00:00          Pirapora  -7.3  2012
27 2012-04-25 23:00:00          Pirapora  -5.7  2012
28 2012-07-14 10:00:00       Camanducaia  -0.5  2012
29 2012-07-20 10:00:00       Camanducaia  -0.4  2012
30 2013-08-29 10:00:00       Camanducaia  -1.5  2013
31 2013-08-28 10:00:00         Rancharia  -1.4  2013
32 2013-08-16 10:00:00       Camanducaia  -1.1  2013
33 2013-08-29 09:00:00       Camanducaia  -1.1  2013
34 2013-08-28 11:00:00         Rancharia  -1.0  2013
35 2014-08-08 10:00:00     Nova Friburgo  -1.1  2014
36 2014-08-06 10:00:00       Maria da Fé  -0.9  2014
37 2014-08-08 09:00:00     Nova Friburgo  -0.9  2014
38 2014-08-07 10:00:00       Maria da Fé  -0.8  2014
39 2014-08-06 09:00:00       Maria da Fé  -0.7  2014
40 2015-06-27 10:00:00       Maria da Fé  -0.3  2015
41 2015-06-27 09:00:00       Maria da Fé  -0.1  2015
42 2015-06-27 08:00:00       Maria da Fé   0.1  2015
43 2015-06-27 11:00:00       Maria da Fé   0.3  2015
44 2015-06-27 10:00:00  Campos do Jordão   0.5  2015
45 2016-06-13 09:00:00    Barra do Turvo  -3.6  2016
46 2016-06-13 10:00:00    Barra do Turvo  -3.6  2016
47 2016-06-13 11:00:00    Barra do Turvo  -3.6  2016
48 2016-06-13 08:00:00    Barra do Turvo  -3.5  2016
49 2016-07-18 10:00:00       Camanducaia  -3.4  2016
50 2006-07-06 09:00:00       Camanducaia  -0.9  2006
51 2006-07-06 10:00:00       Camanducaia  -0.8  2006
52 2006-07-06 08:00:00       Camanducaia  -0.5  2006
53 2006-05-04 10:00:00       Camanducaia  -0.4  2006
54 2006-08-22 08:00:00       Camanducaia  -0.3  2006
55 2003-12-27 15:00:00    Rio de Janeiro  -6.9  2003
56 2003-12-27 12:00:00    Rio de Janeiro  -6.8  2003
57 2003-12-27 18:00:00    Rio de Janeiro  -6.8  2003
58 2003-12-27 16:00:00    Rio de Janeiro  -6.7  2003
59 2003-12-27 13:00:00    Rio de Janeiro  -5.4  2003
60 2004-01-05 17:00:00    Rio de Janeiro  -0.3  2004
61 2004-01-08 12:00:00    Rio de Janeiro   1.1  2004
62 2004-01-06 15:00:00    Rio de Janeiro   1.2  2004
63 2004-01-05 16:00:00    Rio de Janeiro   1.3  2004
64 2004-09-06 16:00:00  Campos do Jordão   1.4  2004
65 2005-08-12 09:00:00       Camanducaia   0.4  2005
66 2005-08-12 10:00:00       Camanducaia   0.4  2005
67 2005-08-12 08:00:00       Camanducaia   0.6  2005
68 2005-08-12 11:00:00       Camanducaia   0.6  2005
69 2005-07-14 10:00:00       Camanducaia   0.9  2005
70 2002-09-03 08:00:00  Campos do Jordão  -1.6  2002
71 2002-09-03 09:00:00  Campos do Jordão  -1.5  2002
72 2002-09-03 07:00:00  Campos do Jordão  -1.4  2002
73 2002-09-03 06:00:00  Campos do Jordão  -1.3  2002
74 2002-09-03 10:00:00  Campos do Jordão  -1.3  2002
75 2001-09-17 08:00:00             Bauru   5.6  2001
76 2001-09-17 07:00:00             Bauru   5.8  2001
77 2001-09-17 09:00:00             Bauru   5.8  2001
78 2001-09-17 10:00:00             Bauru   6.1  2001
79 2001-09-17 06:00:00             Bauru   7.0  2001

Let's see amount of rain in cm by province, and by weather station

In [116]:
group_df = df['prcp'].groupby(df['prov'])

In [120]:
group_df.sum()

prov
ES    102779.4
MG    613471.8
RJ    228718.0
SP    373825.2
Name: prcp, dtype: float64

Looks like MG get's the most rain

In [117]:
group_df_wsid = df['prcp'].groupby(df['wsid'])

In [118]:
group_df_wsid.sum()

wsid
178     6159.6
303    14505.2
304    15284.6
305    11789.0
306    15185.8
307    11128.4
308    13291.6
309     9593.8
310     7554.4
311     4446.6
312    20703.6
313    20385.2
314    10570.0
315    16934.8
316    10133.8
317    17881.8
318    13916.4
319    14066.4
320    13158.6
321    13956.2
322    14391.8
323    13098.8
324    11679.6
325    15755.0
326    14157.8
327    13260.8
328    12681.8
329    17453.0
330     9738.0
331    12830.8
332    12654.6
333    15404.2
334     5625.8
335    10437.6
336    11497.6
337     9587.2
338    14038.6
339    15631.0
340     7891.8
341    10843.4
342     7609.2
343    12661.0
344    11211.4
345    11845.4
346    10299.2
347     6336.8
348     9187.8
349     9802.8
350    10414.4
351     4970.8
352     8867.4
353     8701.0
354     8032.8
355     7749.2
356     8732.0
357     6148.6
358     5606.6
359     6634.4
360     6907.0
361    10954.8
362    10751.2
363    12901.6
364     5729.2
365     5218.4
366        2.2
367      976.0
368     1856.8
369       74.6
370     2923.2
371    15035.8
372    13151.2
373    23106.0
374    16040.6
375     8528.8
376     9699.2
377    12123.6
378    14304.2
379    16227.6
380    12529.6
381    27468.2
382    13666.6
383     6186.2
384    10039.8
385    11079.0
386       78.0
387       87.2
388    10364.0
390     1725.2
391     1117.6
392    16666.0
393    17122.6
394    16638.0
395    13449.4
396    20498.4
397    12481.8
398    19124.4
399    12053.8
400    13098.8
401    10308.6
402    13697.8
403    12248.4
404    10712.4
405    13062.6
406     9503.4
407    10406.8
408    12115.4
409    10712.0
410    10910.4
411     9843.8
412     7959.2
413    10712.2
414     8581.0
415    11925.6
416    11008.6
417    11224.8
418     3846.4
419    10740.6
420     8855.8
421     7651.6
422     9210.4
423     7454.2
Name: prcp, dtype: float64

In [119]:
group_df_wsid.max()

wsid
178     68.6
303     70.2
304     43.8
305     51.8
306     69.4
307     71.2
308     78.4
309     96.8
310     55.0
311     42.8
312     65.0
313     54.4
314     53.6
315     54.8
316     60.8
317     49.8
318     63.0
319     76.2
320     56.4
321     66.2
322     74.8
323     50.2
324     56.2
325     69.0
326     50.0
327     65.0
328     46.0
329     78.4
330     85.4
331     48.6
332     70.6
333     62.0
334     55.2
335     54.2
336     57.8
337     43.6
338     57.2
339     47.8
340     45.8
341     64.0
342     46.2
343     69.8
344     62.0
345     42.8
346     70.4
347     49.4
348     52.0
349     47.6
350     53.6
351     55.6
352     63.0
353     43.6
354     55.0
355    100.0
356     52.2
357     45.8
358     51.8
359     51.4
360     70.2
361     70.4
362     72.4
363     51.0
364     47.8
365     43.4
366      1.4
367     25.2
368     55.0
369     15.0
370     50.0
371     66.2
372     79.8
373     89.0
374     63.6
375     68.8
376     62.8
377     65.2
378     66.2
379     45.0
380     54.4
381     78.4
382     65.2
383     66.6
384     64.0
385     62.8
386     15.6
387      8.8
388     60.8
390     76.2
391     50.8
392     77.8
393     55.2
394     51.0
395     46.8
396     63.2
397     53.8
398     59.0
399     55.4
400     58.6
401     77.0
402     56.6
403     52.4
404     53.0
405     47.8
406     46.6
407     54.0
408     51.6
409     67.0
410     74.2
411     73.4
412     52.8
413     49.4
414     64.0
415     49.8
416     65.8
417     58.2
418     77.6
419     53.6
420     56.8
421     70.0
422     66.8
423     59.2
Name: prcp, dtype: float64